name: Log Analyzer CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  linting:
    name: Linting and Static Analysis
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "${{ runner.workspace }}/.local/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        poetry install --no-root
    - name: Run Flake8
      continue-on-error: true
      run: |
        poetry run flake8 .
    - Name: Run Black
      continue-on-error: true
      run: |
        poetry run black --check .
    - name: Run isort
      continue-on-error: true
      run: |
        poetry run isort --check-only .
    - name: Run MyPy
      run: |
        poetry run mypy . --install-types --non-interactive

  security:
    name: Security Checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "${{ runner.workspace }}/.local/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        poetry install --no-root
    - name: Run Safety
      run: |
        poetry run safety check
    - name: Run Bandit
      run: |
        poetry run bandit -r . --skip B101

  testing:
    name: Testing and Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "${{ runner.workspace }}/.local/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        poetry install
    - name: Run Tests with Coverage
      run: |
        poetry run coverage run -m pytest
        poetry run coverage report -m
        poetry run coverage xml
