name: Log Analyzer CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  linting:
    name: Linting and Static Analysis
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black isort mypy
    - name: Run Flake8
      continue-on-error: true
      run: |
        flake8 .
    - name: Run Black
      run: |
        black --check .
    - name: Run isort
      run: |
        isort --check-only .
    - name: Run MyPy
      run: |
        mypy . --install-types --non-interactive

  security:
    name: Security Checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety bandit
    - name: Run Safety
      run: |
        safety check -r requirements.txt
    - name: Run Bandit
      run: |
        bandit -r . --skip B101

  testing:
    name: Testing and Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest coverage
    - name: Run Tests with Coverage
      run: |
        coverage run -m pytest .
        coverage report -m
        coverage xml

